channels:
  - ome
  - conda-forge
  - joshmoore
  - defaults
  - anaconda
dependencies:
  - python == 3.9.0
  - ipython
  - wheel
  - requests
  - h5py
  - s3fs
  - scikit-image
  - scipy
  - xarray
  - zarr >= 2.7.0
  - go-mc
  - pip
  - boto3
  - pytest-benchmark
  - awscli
  - pyqt
  - botocore
  - pip:
      - ome-zarr
