channels:
  - ome
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python==3.9.0
  - pip==21.0.1
  - snakemake-minimal==6.4.0
  - ptitprince==0.2.5
  - pandas==1.3.4
  - bioformats2raw==0.3.0
  - raw2ometiff==0.3.0
  - nodejs==17.1
  - pip:
    - generate-tiff-offsets==0.1.7
