- hosts: all
  tasks:

    - apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'python3', 'python3-pip', 'awscli']

    - pip: name={{ item }} executable=pip3
      loop: ['docker', 'docker-compose']

    - ansible.builtin.git:
        repo: 'https://github.com/ome/ngff-latency-benchmark'
        dest: 'ngff-latency-benchmark'

- hosts: servers
  tasks:

    - docker_compose:
        project_src: "ngff-latency-benchmark"
        state: "present"
        services:
          - "nginx"
