- hosts: servers
  roles:
  - role: ome.nginx_proxy

  vars:
    nginx_proxy_direct_locations:
    - location: "/"
      root: "/data"

- hosts: clients

  roles:
    - role: ome.docker
      docker_use_ipv4_nic_mtu: True

  tasks:
  - name: install docker-python
    become: yes
    yum:
      name: docker-python
      state: present
